let Constants = {
    IDENTITY_LENGTH : 100,
    SINGATURE_LENGTH : 256,
    PAYWORD_LENGTH : 40,
    DATE_LENGTH : 10,
    PRICE_LENGTH : 10,
    BOOK_ID_LENGTH : 10,
    HASH_CHAIN_LENGTH : 10,
    RSA_KEY_LENGTH :271,
    CERTIFICATE_LENGTH : 1028,
    CERTIFICATE_MESSAGE_LENGTH : 772
}

module.exports = Constants;
